config/routes.rb
Rails.application.routes.draw do
resources :pages
resources :products
resource :cart
resources :order_items
resources :category
resources :charges
resources :addresses

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :users
  resources :products, :images

  root 'pages#index'

  get 'pages/home' => 'pages#home'
  get 'pages/category_page' => 'pages#category_page'

  #get '/product_details/:id' => 'pages#product_details'
  #get '/product/:id' => 'pages#product_details'
  #put '/product_details/:id' => 'pages#product_details'



  get 'pages/user_profile' => 'pages#user_profile'
  get 'pages/admin_dashboard' => 'pages#admin_dashboard'
  get 'pages/incart' => 'pages#incart'
  get 'carts/addresses' => 'carts/addresses', as: 'carts_addresses'
  get 'carts/payment' => 'carts/payment', as: 'payment'
  #get 'registration/new' => 'registration/new', as: 'new'
  get 'charges/new' => 'charges/new', as: 'charges_new'
  get 'addresses/new' => 'addresses/new', as: 'addresses_new'
  #
  # get 'order_items/order' => 'order_items#order'
  # get 'carts/show' => 'carts#show'







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
belongs_to :user
has_many :addresses 
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :products, through: :colors_products
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :products, through: :colors_products
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_one :user
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def shipping
    self[:shipping] = 30
  end

  def total
    self[:total] = subtotal + shipping
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  has_one :image
  has_one :user
  has_one :color
  has_one :size

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
has_one :image
#serialize :color_id, Array
#has_many :order_items
#has_many :product_colors
has_and_belongs_to_many :colors,  :join_table => "colors_products"
has_and_belongs_to_many :sizes,  :join_table => "products_sizes"
has_and_belongs_to_many :categories,  :join_table => "categories_products"
has_and_belongs_to_many :brands
has_one :style





end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color
end

app/models/size.rb
class Size < ApplicationRecord
  has_and_belongs_to_many :products

end

app/models/style.rb
class Style < ApplicationRecord
  has_many :products

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
    @order_items=OrderItem.all.paginate(page: params[:page], per_page: 8)
    @order_itemss=OrderItem.where(:user_id => current_user.id)
    @num_of_items=@order_itemss.to_a.size
    @orders=Order.all
    @uid=User.find_by_id(current_user)
    @images=Image.find_by_id(@product)
    @brands=Brand.all
    @sizes=Size.all
    @styles=Style.all
    @colors=Color.all
    @categories=Category.all
    @order=Order.find_by_id(@order_items)
    @orders=Order.all
    @cart=Order.find_by_id(@order_items)
  end

  def addresses
  @order_items = current_order.order_items
   @order_items=OrderItem.all.paginate(page: params[:page], per_page: 8)
   @order_itemss=OrderItem.where(:user_id => current_user.id)
   @uid=User.find_by_id(current_user)
   @num_of_items=@order_itemss.to_a.size
   @images=Image.find_by_id(@product)
   @brands=Brand.all
   @sizes=Size.all
   @styles=Style.all
   @colors=Color.all
   @categories=Category.all
   @order=Order.find_by_id(@order_items)
   @cart=Order.find_by_id(@order_items)
   @addresses=Address.all
  end

  def payment
    @order_items = current_order.order_items
   @order_items=OrderItem.all.paginate(page: params[:page], per_page: 8)
   @order_itemss=OrderItem.where(:user_id => current_user.id)
   @uid=User.find_by_id(current_user)
   @num_of_items=@order_itemss.to_a.size
   @images=Image.find_by_id(@product)
   @brands=Brand.all
   @sizes=Size.all
   @styles=Style.all
   @colors=Color.all
   @categories=Category.all
   @order=Order.find_by_id(@order_items)
   @cart=Order.find_by_id(@order_items)

  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  
end

app/views/carts/_address_forms.html.erb
lalal

app/views/carts/_cart_row.html.erb
  <div class="row prozivodi">

      <%= form_for order_item, remote: true do |f| %>

      <div class="col-md-3">

        <img class="img-responsive slikica" src="<%= product.imgurl %>" alt="">
      </div>


      <div class="col-md-3">
        <br/> <br/>
        <p> Model: <%= product.name %></p>
        <p>  Velicina: <br/></p>
        <p>  ID: <%= product.id %></p>
      </div>


      <div class="col-md-3 text-right">
        <!-- <p class="text-right">Cijena: <span style="color: green"><%=order_item.unit_price %></span></p> -->
        <p class="">Cijena:<br/> <span style="color: black; font-weight: bold; font-size: 22px;"><%= order_item.total_price %></span></p>

          <span id="udesno"><%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %></span>

            <div class="btn-group">
              <%= f.submit "Dodaj", class: "btn korpa_button" %>
              <%= link_to "Ukloni", order_item, { data: { confirm: "Jeste li sigurni da zelite proizvod '#{order_item.product.name}' ukloniti iz Vase korpe?" }, method: :delete, remote: true, class: "btn kupi_button" } %>
            </div>
          </div>

      <% end %>


  </div>




<style>
#udesno{
float: right !important;
}
.row{
  margin-top: 10px;
  margin-bottom: 30px;
}


.form-control{
  width: auto;
}
.kupi_button {
	background-color:#080404;
	-moz-border-radius:4px;
	-webkit-border-radius:4px;
	border-radius:4px;
	border:1px solid #fff5ff;
	display:inline-block;
	cursor:pointer;
	color:#f5e7f5;
	font-family:Arial;
	font-size:12px;
	padding:5px 8px;
	text-decoration:none;
}
.kupi_button:hover {
	background-color:#f70f1a;
  text-decoration: none;

}
.kupi_button:active {
	position:relative;
	top:1px;
}


.korpa_button {
	background-color:#ffffff;
	-moz-border-radius:4px;
	-webkit-border-radius:4px;
	border-radius:4px;
	border:1px solid #dcdcdc;
	display:inline-block;
	cursor:pointer;
	color:black !important;
	font-family:Arial;
	font-size:12px;
	padding:5px 8px;
	text-decoration:none;
  font-weight: bold;
}
.korpa_button:hover {
	background-color: #ffa31a;
  text-decoration: none;
}
.korpa_button:active {
	position:relative;
	top:1px;
}

.slikica{
  width: 250px;
  height: 200px;
}
</style>

app/views/carts/_shopping_cart.html.erb
<h3> Vasa korpa </h3>
<br/>
<div class="row">
  <div class="col-md-offset-9">
    <img src="korpa.png" id="korpa" />
    <br/><br/><br/>
<%= render 'vasa_korpa'%>
<div id="dugmici">
<%= link_to 'ODUSTANI', root_path, class:"odustani_btn" %>
<%= link_to 'NASTAVI', addresses_new_path, class:"nastavi_btn" %>
</div>
</div>
</div>

<div class="u_korpi">
<% if @order_itemss.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.
  </p>
<% else %>
  <% @order_itemss.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true, user_id: current_user.id %>
  <% end %>
<% end %>
</div>



<style>
.u_korpi{
  margin-top: -300px;
}
</style>

app/views/carts/_vasa_korpa.html.erb
    <div class="kockica">
    <strong> Narudzba </strong><span class="sivo dodatak"><%= @num_of_items %> proizvoda</span>
    <div class="desno">


    <p class="sivo">  Cijena: <br/></p> <span class="dodatak"><strong><%= current_order.subtotal %>KM </strong></span>
      <br/><br/>
    <p class="sivo">  Dostava: <br/></p> <span class="dodatak"><strong> <%= current_order.shipping %> KM </strong></span>
      <br/>
      <hr/>
    <span class="sivo">Ukupno </span> <span class="dodatak"><strong> <%= current_order.total %> KM  </strong></span>
    </div>
    </div>
    <!-- <% cui=current_user.id %>
    <% @orders=Order.find_by_id(:id) %>

    <%=  current_order.id %> -->




<style>
.sivo{
  color:gray;
  font-weight: lighter;
  font-size: 16px;
}
.dodatak{
  font-size: 18px;
}

#korpa{
  float: right;
  height: auto;
  width: 100%;
}
#dostava{
  float: right;
  height: auto;
  width: 100%;
}
#dugmici{
  float: right;
  padding-top: 15px;
}
.kockica{
  width: 350px;
  height: auto;
  border: 2px solid;
  border-color: #404040;
  padding: 20px;
}
.desno{
text-align: right;
}

.odustani_btn {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background-color:#ffffff;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
	border-radius:3px;
	border:1px solid #000000;
	display:inline-block;
	cursor:pointer;
	color:#363236 !important;
	font-family:Verdana;
	font-size:14px;
	padding:11px 24px;
	text-decoration:none;
}
.odustani_btn:hover {
	background-color:#f6f6f6;
  text-decoration:none;

}
.odustani_btn:active {
	position:relative;
	top:1px;
}

.nastavi_btn {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background-color: #1a1a1a;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
	border-radius:3px;
	border:1px solid #363236;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Verdana;
	font-size:14px;
  font-weight: bold;
	padding:11px 24px;
	text-decoration:none;
}
.nastavi_btn:hover {
	background-color:#575757;
  text-decoration:none;
  color:#ffffff !important;
}
.nastavi_btn:active {
	position:relative;
	top:1px;
}

</style>

app/views/carts/addresses.html.erb
<h3> Adresa za dostavu </h3>
<br/>

<div class="row">
  <div class="col-md-offset-9">

    <img src="/dostava.png" id="korpa" />

    <br/><br/><br/>

<%= render 'vasa_korpa' %>

<div id="dugmici">
<%= link_to 'NAZAD', cart_path, class:"odustani_btn" %>
<%= link_to 'NASTAVI', charges_new_path, class:"nastavi_btn" %>
</div>

</div>
</div>

<div class="address1">
    <%= render 'address_forms' %>
</div>

<div class="address2">

</div>



<style>

</style>

app/views/carts/payment.html.erb
<h3> Potvrda i placanje </h3>
<br/>

<div class="row">
  <div class="col-md-offset-9">

    <img src="/placanje.png" id="korpa" />

    <br/><br/><br/>

<%= render 'vasa_korpa' %>

<div id="dugmici">
  <span id="stripe">stripe  &nbsp;</span>
  <span class="plati_btn"> <%= link_to(addresses_path)do %><strong> Plati <%=current_order.total%></strong><%end %></span>
</div>

</div>
</div>




<style>
#stripe{
  font-weight: bolder;
  color: #bfbfbf !important;
  font-size: 16px;
}
.plati_btn {
	-moz-box-shadow: 0px 1px 0px 0px #f0f7fa;
	-webkit-box-shadow: 0px 1px 0px 0px #f0f7fa;
	box-shadow: 0px 1px 0px 0px #f0f7fa;
	background-color:#518afc;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
	border-radius:3px;
	border:1px solid #035a8c;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Verdana;
	font-size:14px;
	padding:8px 39px;
	text-decoration:none;
	text-shadow:0px -1px 0px #5b6178;
}
.plati_btn:hover {
	background-color:#075dbf;
  text-decoration:none;
  color: white !important;
}
.plati_btn:active {
	position:relative;
	top:1px;
}

</style>

app/views/carts/show.html.erb
<div>
  <%= render "shopping_cart" %>
</div>