config/routes.rb
Rails.application.routes.draw do
resources :pages
resources :products
resource :cart
resources :order_items
resources :category
resources :charges
resources :addresses

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :users
  resources :products, :images

  root 'pages#index'

  get 'pages/home' => 'pages#home'
  get 'pages/category_page' => 'pages#category_page'

  #get '/product_details/:id' => 'pages#product_details'
  #get '/product/:id' => 'pages#product_details'
  #put '/product_details/:id' => 'pages#product_details'



  get 'pages/user_profile' => 'pages#user_profile'
  get 'pages/admin_dashboard' => 'pages#admin_dashboard'
  get 'pages/incart' => 'pages#incart'
  get 'carts/addresses' => 'carts/addresses', as: 'carts_addresses'
  get 'carts/payment' => 'carts/payment', as: 'payment'
  #get 'registration/new' => 'registration/new', as: 'new'
  get 'charges/new' => 'charges/new', as: 'charges_new'
  get 'addresses/new' => 'addresses/new', as: 'addresses_new'
  #
  # get 'order_items/order' => 'order_items#order'
  # get 'carts/show' => 'carts#show'







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
belongs_to :user
has_many :addresses 
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :products, through: :colors_products
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :products, through: :colors_products
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_one :user
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def shipping
    self[:shipping] = 30
  end

  def total
    self[:total] = subtotal + shipping
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  has_one :image
  has_one :user
  has_one :color
  has_one :size

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
has_one :image
#serialize :color_id, Array
#has_many :order_items
#has_many :product_colors
has_and_belongs_to_many :colors,  :join_table => "colors_products"
has_and_belongs_to_many :sizes,  :join_table => "products_sizes"
has_and_belongs_to_many :categories,  :join_table => "categories_products"
has_and_belongs_to_many :brands
has_one :style





end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color
end

app/models/size.rb
class Size < ApplicationRecord
  has_and_belongs_to_many :products

end

app/models/style.rb
class Style < ApplicationRecord
  has_many :products

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @order_itemss=OrderItem.where(:user_id => current_user.id)
    @num_of_items=@order_itemss.to_a.size
    @addresses=Address.all
end

def create
  # Amount in cents
  @amount_price = (current_order.total*100).round(-1)
  @amount=@amount_price.to_i

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'abhShoes',
    :currency    => 'bam'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  
end

app/views/charges/create.html.erb
<h2>Kupovina uspjesno obavljena! <strong><br/> Racun: <%= current_order.total %> KM</strong>!</h2>

app/views/charges/new.html.erb
<br/><br/>
<h4> Adresa za dostavu i adresa za racun </h4>
<div class="row">
  <div class="col-md-3"
  <% @adress_info=Address.where(:user_id=>current_user.id) %>
    <% for @a in @adress_info %>
  <%= @a.ime_prezime1 %><br/>
  <%= @a.address1 %><br/>
  <%= @a.city1 %><br/>
  <%= @a.region1 %><br/>
  <%= @a.zip1 %><br/>
  <%= @a.country1 %><br/>
  <%= @a.telephone1 %><br/>
  <% end %>
  </div>
<div class="col-md-3"
<% @adress_info=Address.where(:user_id=>current_user.id) %>
  <% for @a in @adress_info %>
<%= @a.ime_prezime2 %><br/>
<%= @a.address2 %><br/>
<%= @a.city2 %><br/>
<%= @a.region2 %><br/>
<%= @a.zip2 %><br/>
<%= @a.country2 %><br/>
<%= @a.telephone2 %><br/>
<% end %>
</div>

<div class="charge_kolona">
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

    <div class="col-md-6 korpa">

      <img src="/placanje.png" id="korpa" />
      <br/><br/><br/>

  <%= render '/carts/vasa_korpa' %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button dugme"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-name="abhShoes"
          data-description="Placanje karticom"
          data-email="<%= current_user.email %>"
          data-label="Plati <%= current_order.total %> KM"
          data-amount="<%= current_order.total*100 %>"
          data-locale="auto"></script>
      </div>


<% end %>

    </div>
</div>

<style>
.stripe-button-el{
  float: right !important;
  margin-top: 10px !important;
  margin-right: -120% !important;
}
.plati_btn {
	-moz-box-shadow: 0px 1px 0px 0px #f0f7fa;
	-webkit-box-shadow: 0px 1px 0px 0px #f0f7fa;
	box-shadow: 0px 1px 0px 0px #f0f7fa;
	background-color:#518afc;
	-moz-border-radius:3px;
	-webkit-border-radius:3px;
	border-radius:3px;
	border:1px solid #035a8c;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Verdana;
	font-size:14px;
	padding:8px 39px;
	text-decoration:none;
	text-shadow:0px -1px 0px #5b6178;
}
.plati_btn:hover {
	background-color:#075dbf;
  text-decoration:none;
  color: white !important;
}
.plati_btn:active {
	position:relative;
	top:1px;
}
#korpa{
  width: 350px !important;
  margin-right: -118% !important;
}
.charge_kolona{
float: right !important;
}
.korpa{
margin-right: -20% !important;
}
</style>