config/routes.rb
Rails.application.routes.draw do
resources :pages
resources :products
resource :cart
resources :order_items
resources :category
resources :charges
resources :addresses

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :users
  resources :products, :images

  root 'pages#index'

  get 'pages/home' => 'pages#home'
  get 'pages/category_page' => 'pages#category_page'

  #get '/product_details/:id' => 'pages#product_details'
  #get '/product/:id' => 'pages#product_details'
  #put '/product_details/:id' => 'pages#product_details'



  get 'pages/user_profile' => 'pages#user_profile'
  get 'pages/admin_dashboard' => 'pages#admin_dashboard'
  get 'pages/incart' => 'pages#incart'
  get 'carts/addresses' => 'carts/addresses', as: 'carts_addresses'
  get 'carts/payment' => 'carts/payment', as: 'payment'
  #get 'registration/new' => 'registration/new', as: 'new'
  get 'charges/new' => 'charges/new', as: 'charges_new'
  get 'addresses/new' => 'addresses/new', as: 'addresses_new'
  #
  # get 'order_items/order' => 'order_items#order'
  # get 'carts/show' => 'carts#show'







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cart.rb
class Cart < ApplicationRecord
belongs_to :user
has_many :addresses 
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :products, through: :colors_products
end

app/models/color.rb
class Color < ApplicationRecord
  has_and_belongs_to_many :products
  has_many :products, through: :colors_products
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_one :user
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def shipping
    self[:shipping] = 30
  end

  def total
    self[:total] = subtotal + shipping
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  has_one :image
  has_one :user
  has_one :color
  has_one :size

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
has_one :image
#serialize :color_id, Array
#has_many :order_items
#has_many :product_colors
has_and_belongs_to_many :colors,  :join_table => "colors_products"
has_and_belongs_to_many :sizes,  :join_table => "products_sizes"
has_and_belongs_to_many :categories,  :join_table => "categories_products"
has_and_belongs_to_many :brands
has_one :style





end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color
end

app/models/size.rb
class Size < ApplicationRecord
  has_and_belongs_to_many :products

end

app/models/style.rb
class Style < ApplicationRecord
  has_many :products

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  
end

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
  <%= render '/layouts/nav_pages_user' %>
<% else %>
  <%= render '/layouts/nav_pages_guest' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<style>
ul li a, a{
  color: white !important;
  font-weight: bold;
}

.banner
{
  background-image: url(backf.png);
  background-repeat: no-repeat;
  background-size: cover;
  min-height:200px;
}
ul li, a:hover{
  color: black !important;
  background-color: background-color: rgba(0,0,0,0.0) !important;
}

.banner .row
{
  text-align:center;
  margin-top:50px;
}
.banner
{
  height: 500px;
}
.opaque-navbar {
    background-color: rgba(0,0,0,0.5);
  /* Transparent = rgba(0,0,0,0) / Translucent = (0,0,0,0.5)  */
    height: 60px;
    border-bottom: 0px;
  color: white;
}

.opaque-navbar.opaque {
    height: 60px;
    transition: background-color .5s ease 0s;
}

ul.dropdown-menu {
  background-color: rgba(0,0,0,0.5);
}



</style>

</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top opaque-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
  </button>
      <a class="navbar-brand" href="#"><%= link_to "abhShoes", root_path %></a>
    </div>
    <div class="collapse navbar-collapse" id="navMain">
      <ul class="nav navbar-left">
        <% for @c in @categories %>
        <% @cid=Category.find_by_id(@c) %>
        <% @cname=Category.find_by_category_name(@c) %>
        <li><%= link_to(category_path(@cid)) do %><strong><%= @c.category_name %></strong><% end %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-right">
        <li><%= link_to('Log in', new_user_session_path) %></li>
         <li><a href="#">|</a></li>
        <li><%= link_to('Register', new_user_registration_path) %></li>
      </ul>

    </div>
  </div>
</div>
<section class="banner">
<div class="container">
  <div class="row">
  <!-- here goes that background photo -->
  </div>
  </div>
  </section>
</body>
</html>

<script>

  $(window).scroll(function() {
    if($(this).scrollTop() > 50)  /*height in pixels when the navbar becomes non opaque*/
    {
        $('.opaque-navbar').addClass('opaque');
    } else {
        $('.opaque-navbar').removeClass('opaque');
    }
});

</script>

app/views/layouts/_nav_pages_guest.html.erb
<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<style>
ul li a, a{
  color: white !important;
  font-weight: bold;
}
ul li, a:hover{
  color: black !important;
  background-color: background-color: rgba(0,0,0,0.0) !important;
}

.banner
{
  background:black;
  height:60px;
}
.banner .row
{
  text-align:center;
  margin-top:50px;
}
.banner
{
  height: 60px;
}


ul.dropdown-menu {
  background-color: rgba(0,0,0,0.5);
}



</style>

</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
  </button>
      <a class="navbar-brand" href="#"><%= link_to "abhShoes", root_path %></a>
    </div>
    <div class="collapse navbar-collapse" id="navMain">
      <ul class="nav navbar-left">
        <% for @c in @categories %>
        <% @cid=Category.find_by_id(@c) %>
        <% @cname=Category.find_by_category_name(@c) %>
        <li><%= link_to(category_path(@cid)) do %><strong><%= @c.category_name %></strong><% end %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-right">
        <li><%= link_to('Log in', new_user_session_path) %></li>
         <li><a href="#">|</a></li>
        <li><%= link_to('Register', new_user_registration_path) %></li>
      </ul>

    </div>
  </div>
</div>
<section class="banner">
<div class="container">

  </div>
  </section>
</body>
</html>

<script>

  $(window).scroll(function() {
    if($(this).scrollTop() > 50)  /*height in pixels when the navbar becomes non opaque*/
    {
        $('.opaque-navbar').addClass('opaque');
    } else {
        $('.opaque-navbar').removeClass('opaque');
    }
});

</script>

app/views/layouts/_nav_pages_user.html.erb
<!DOCTYPE html>
<html>
<head>
    <% if request.ssl? %>
      <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% else %>
      <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% end %>

    <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<style>
ul li a, a{
  color: white !important;
  font-weight: bold;
}
ul li, a:hover{
  color: black !important;
  background-color: background-color: rgba(0,0,0,0.0) !important;
}

.banner
{
  background:black;
}
.banner .row
{
  text-align:center;
  margin-top:50px;
}
.banner
{
  height: 60px;
}

ul.dropdown-menu {
  background-color: rgba(0,0,0,0.5);

}

#cart_img{
height:28px;
width:28px;
}

.num_items{
background-color: red;
padding: 1px;
display: inline-flex;
width: 400%;
height: 50%;
font-size: 18px;
border: 2px solid red;
border-radius: 20px;
}

</style>

</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top opaque-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
  </button>
      <a class="navbar-brand" href="#"><%= link_to "abhShoes", root_path %></a>
    </div>
    <div class="collapse navbar-collapse" id="navMain">
      <ul class="nav navbar-left">
        <% for @c in @categories %>
        <% @cid=Category.find_by_id(@c) %>
        <% @cname=Category.find_by_category_name(@c) %>
        <li><%= link_to(category_path(@cid)) do %><strong><%= @c.category_name %></strong><% end %></li>
        <% end %>
      </ul>
            <ul class="nav navbar-right">
        <li>


          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><%= current_user.username %></span></button>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to('Edit Profile', edit_user_registration_path) %></a></li>
              <li class="divider"></li>
              <li><a href="#"><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></a></li>
            </ul>
          </div>

        </li>

        <li><a href="#">| </a></li>
      <%= link_to (image_tag('http://szemuveglencse.hu/wp-content/regoptika/shopingbasket.png', :id=>"cart_img", :class=>"cart-text")), cart_path %><div class="num_items"> <%= @num_of_items %></div>

      </ul>
    </div>
  </div>
</div>
<section class="banner">
<div class="container">
  <div class="row">
  <!-- here goes that background photo -->
  </div>
  </div>
  </section>
</body>
</html>

<script>

  $(window).scroll(function() {
    if($(this).scrollTop() > 50)  /*height in pixels when the navbar becomes non opaque*/
    {
        $('.opaque-navbar').addClass('opaque');
    } else {
        $('.opaque-navbar').removeClass('opaque');
    }
});

</script>
<script src="content/js/jquery.min.js"></script>
<script src="content/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>

app/views/layouts/_nav_user.html.erb
<!DOCTYPE html>
<html>
<head>
    <% if request.ssl? %>
      <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% else %>
      <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% end %>

    <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<style>
a{
  text-decoration: none;
}
ul li a, a{
  color: white !important;
  font-weight: bold;
}
ul li, a:hover{
  color: black !important;
  background-color: background-color: rgba(0,0,0,0.0) !important;
}

.banner
{
  background-image: url(backf.png);
  background-repeat: no-repeat;
  background-size: cover;
  min-height:200px;
}
.banner .row
{
  text-align:center;
  margin-top:50px;
}
.banner
{
  height: 500px;
}
.opaque-navbar {
    background-color: rgba(0,0,0,0.2);
  /* Transparent = rgba(0,0,0,0) / Translucent = (0,0,0,0.5)  */
    height: 60px;
    border-bottom: 0px;
  color: white;
}

.opaque-navbar.opaque {
    height: 60px;
    transition: background-color .5s ease 0s;
}

ul.dropdown-menu {
  background-color: rgba(0,0,0,0.5);

}

#cart_img{
height:28px;
width:28px;
}

.num_items{
background-color: red;
padding: 1px;
display: inline-flex;
width: 400%;
height: 50%;
font-size: 18px;
border: 2px solid red;
border-radius: 20px;
}

</style>

</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top opaque-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
  </button>
      <a class="navbar-brand" href="#"><%= link_to "abhShoes", root_path %></a>
    </div>
    <div class="collapse navbar-collapse" id="navMain">
      <ul class="nav navbar-left">
        <% for @c in @categories %>
        <% @cid=Category.find_by_id(@c) %>
        <% @cname=Category.find_by_category_name(@c) %>
        <li><%= link_to(category_path(@cid)) do %><strong><%= @c.category_name %></strong><% end %></li>
        <% end %>
      </ul>
            <ul class="nav navbar-right">
        <li>


          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><%= current_user.username %></span></button>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to('Edit Profile', edit_user_registration_path) %></a></li>
              <li class="divider"></li>
              <li><a href="#"><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></a></li>
            </ul>
          </div>

        </li>

        <li><a href="#">| </a></li>
      <%= link_to (image_tag('http://szemuveglencse.hu/wp-content/regoptika/shopingbasket.png', :id=>"cart_img", :class=>"cart-text")), cart_path %><div class="num_items"> <%= @num_of_items %></div>

      </ul>
    </div>
  </div>
</div>
<section class="banner">
<div class="container">
  <div class="row">
  <!-- here goes that background photo -->
  </div>
  </div>
  </section>
</body>
</html>

<script>

  $(window).scroll(function() {
    if($(this).scrollTop() > 50)  /*height in pixels when the navbar becomes non opaque*/
    {
        $('.opaque-navbar').addClass('opaque');
    } else {
        $('.opaque-navbar').removeClass('opaque');
    }
});

</script>
<script src="content/js/jquery.min.js"></script>
<script src="content/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>

app/views/layouts/_navindex.html.erb
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/pages/_category.html.erb
<div class="container">


  <div class="row">
    <div class="col-md-6 offset-md-3">

</div>
</div>


<div class="row list_of_shoes">
  <div class="col-md-3 offset-md-1">
    <br/> <br/>
 </div>
</div>


<div class="row">

  <div class="col-md-3 offset-md-0">
  <b> FILTER </b>
  </div>

  <div class="col-md-3 category__name">
  <b>  Selected category name... </b>
  </div>

  <div class="col-md-3 offset-md-9">
    <div class="cijena">
      <label for="sel1" class="label1">Cijena:</label>
      <select id="cijena">
        <option value="<%= Product.order(:price) %>">Od vece ka manjoj</option>
        <option value="product.price_DESC=1">Od manje ka vecoj</option>
      </select>
    </div>
    </div>

  </div>

  <div class="row list_of_shoes">
    <div class="col-md-3 offset-md-1">
      <br/> <br/>
   </div>
  </div>


<div class="row">

  <div class="col-md-3">

    <div class="filters">
      <label for="sel2">Brend:</label>
      <select class="form-control" id="sel2">
        <% for @b in @brands %>
        <option><%= @b.brand_name %></option>
            <% end %>
      </select>

    </div>

    <div class="filters">
      <label for="sel2">Velicina:</label>
      <select class="form-control" id="sel2">
        <% for @sz in @sizes %>
        <option><%= @sz.product_size %></option>
        <% end %>
      </select>
    </div>

    <div class="filters">
      <label for="sel2">Boja:</label>
      <select class="form-control" id="sel2">
        <% for @cl in @colors %>
        <option> <%= @cl.color_name %></option>
        <% end %>
      </select>
    </div>

    <div class="filters">
      <label for="sel2">Stil:</label>
      <select class="form-control" id="sel2">
        <% for @ss in @styles %>
        <option><%= @ss.style_name %></option>
        <% end %>
      </select>
    </div>

    <div class="filters">
      <label for="sel2">Cijena:</label>
      <select class="form-control" id="sel2">
        <option><%= link_to '5-41', @products_path, price_min: 5, price_max: 41 %></option>
        <option><%= link_to '41-46', @products_path, price_min: 41, price_max: 46 %></option>
        <option><%= link_to '46-50', @products_path, price_min: 46, price_max: 50 %></option>


      </select>
    </div>

  </div>



  <div class="col-md-9">
    <% for @i in @images %>
      <% @p=Product.find_by_id(@i.id)%>
      <% @col_img=Color.find_by_id(@p.id)%>
      <% @pcol= Product.find(@p).colors %>
      <% @pcolurl= Color.find_by_id(@pcol) %>

      <div class="col-md-3">
          <%= link_to image_tag(@i.img_1, :class=>"img-responsive shoe_images imgs", :title=>@p.category_id), product_path(@p)%>
          <p><%= @p.name %></p> <br/>
          <p id="cijena_proizvoda">$<%= @p.price %></p>
          <% for @pc in @pcol %>
          <img id="boja_proizvoda" src="<%= @pc.color_img %>" title="<%= @pc.color_name %>" />
          <% end %>
      </div>
    <% end %>


    </div>
      </div>


    <div class="row ">
      <div class="col-md-6 offset-md-3">
        <center>
        <nav aria-label="Pages">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true" class="pages">&laquo;</span>
                <span class="sr-only pages">Previous</span>
              </a>
            </li>
            <li class="page-item"><a class="page-link pages" href="#">1</a></li>
            <li class="page-item"><a class="page-link pages" href="#">2</a></li>
            <li class="page-item"><a class="page-link pages" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true" class="pages">&raquo;</span>
                <span class="sr-only pages">Next</span>
              </a>
            </li>
          </ul>
        </nav>
      </center>
      </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy;abhShoes. All rights reserved.</p>
            </div>
        </div>
    </footer>

    </div>

    <style>
    .pages{
      color: black !important;
    }
    .shoe_images{
      margin-bottom: 5px !important;
      margin-right: 0px !important;
    }
    .label1{
      display: inline-block;
    }

    .category__name{
      margin-bottom: 30px !important;
    }

    .cijena{
      margin-bottom: 30px !important;
      margin-left: 45px;
      display: inline;
    }

    #cijena{
      border: 0px;
      border-radius: 7px;
      height: 30px;
      padding: 4px;
    }

    select option{
      padding: 0px !important;
    }
    .filters{
      margin-bottom: 50px;
    }
    .form-control{
      padding-bottom: 1px !important;
      padding-top: 2px !important;
    }
    .imgs{
      height: 135px;
      width: 180px;
    }

    #boja_proizvoda{
    height: 10px;
    width: 10px;
    }
    </style>

app/views/pages/category_page.html.erb
<div class="container">


  <div class="row">
    <div class="col-md-6 offset-md-3">

</div>
</div>


<div class="row list_of_shoes">
  <div class="col-md-3 offset-md-1">
    <br/> <br/>
 </div>
</div>


<div class="row">

  <div class="col-md-3 offset-md-0">
  <b> FILTER </b>
  </div>

  <div class="col-md-3 category__name">
  <b>  Selected category name... </b>
  </div>

  <div class="col-md-3 offset-md-9">
    <div class="cijena">
      <label for="sel1" class="label1">Cijena:</label>
      <select id="cijena">
        <option value="<%= Product.order(:price) %>">Od vece ka manjoj</option>
        <option value="product.price_DESC=1">Od manje ka vecoj</option>
      </select>
    </div>
    </div>

  </div>

  <div class="row list_of_shoes">
    <div class="col-md-3 offset-md-1">
      <br/> <br/>
   </div>
  </div>


<div class="row">

  <div class="col-md-3">

    <div class="filters">
      <label for="sel2">Brend:</label>
      <select class="form-control" id="sel2">
        <% for @b in @brands %>
        <option><%= @b.brand_name %></option>
            <% end %>
      </select>

    </div>

    <div class="filters">
      <label for="sel2">Velicina:</label>
      <select class="form-control" id="sel2">
        <% for @sz in @sizes %>
        <option><%= @sz.product_size %></option>
        <% end %>
      </select>
    </div>

    <div class="filters">
      <label for="sel2">Boja:</label>
      <select class="form-control" id="sel2">
        <% for @cl in @colors %>
        <option> <%= @cl.color_name %></option>
        <% end %>
      </select>
    </div>

    <div class="filters">
      <label for="sel2">Stil:</label>
      <select class="form-control" id="sel2">
        <% for @ss in @styles %>
        <option><%= @ss.style_name %></option>
        <% end %>
      </select>
    </div>

    <div class="filters">
      <label for="sel2">Cijena:</label>
      <select class="form-control" id="sel2">
        <option><%= link_to '5-41', @products_path, price_min: 5, price_max: 41 %></option>
        <option><%= link_to '41-46', @products_path, price_min: 41, price_max: 46 %></option>
        <option><%= link_to '46-50', @products_path, price_min: 46, price_max: 50 %></option>


      </select>
    </div>

  </div>

<div class="col-md-9">

  <% for @i in @images %>
    <% @p=Product.find_by_id(@i.id)%>
    <% @col_img=Color.find_by_id(@p.id)%>
    <% @pcol= Product.find(@p).colors %>
    <% @pcolurl= Color.find_by_id(@pcol) %>

    <div class="col-md-3">
        <%= link_to image_tag(@i.img_1, :class=>"img-responsive shoe_images imgs"), product_path(@p)%>
        <p><%= @p.name %></p> <br/>
        <p id="cijena_proizvoda">$<%= @p.price %></p>
        <% for @pc in @pcol %>
        <img id="boja_proizvoda" src="<%= @pc.color_img %>" title="<%= @pc.color_name %>" />
        <% end %>
    </div>
  <% end %>


  </div>

</div>


<div class="row ">
  <div class="col-md-6 offset-md-3">
    <center>
    <nav aria-label="Pages">
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true" class="pages">&laquo;</span>
            <span class="sr-only pages">Previous</span>
          </a>
        </li>
        <li class="page-item"><a class="page-link pages" href="#">1</a></li>
        <li class="page-item"><a class="page-link pages" href="#">2</a></li>
        <li class="page-item"><a class="page-link pages" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true" class="pages">&raquo;</span>
            <span class="sr-only pages">Next</span>
          </a>
        </li>
      </ul>
    </nav>
  </center>
  </div>
</div>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy;abhShoes. All rights reserved.</p>
        </div>
    </div>
</footer>

</div>

<style>
.pages{
  color: black !important;
}
.shoe_images{
  margin-bottom: 5px !important;
  margin-right: 0px !important;
}
.label1{
  display: inline-block;
}

.category__name{
  margin-bottom: 30px !important;
}

.cijena{
  margin-bottom: 30px !important;
  margin-left: 45px;
  display: inline;
}

#cijena{
  border: 0px;
  border-radius: 7px;
  height: 30px;
  padding: 4px;
}

select option{
  padding: 0px !important;
}
.filters{
  margin-bottom: 50px;
}
.form-control{
  padding-bottom: 1px !important;
  padding-top: 2px !important;
}
.imgs{
  height: 135px;
  width: 180px;
}

#boja_proizvoda{
height: 10px;
width: 10px;
}
</style>